# Generated by Django 5.1.6 on 2025-03-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.TextField(max_length=1200, null=True),
        ),
    ]
