# Generated by Django 5.1.6 on 2025-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0003_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hero-carousel/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("link", models.URLField(default="/about")),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
