# Generated by Django 5.1.6 on 2025-03-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0004_herocarousel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="herocarousel",
            name="link",
        ),
    ]
