# Generated by Django 5.1.6 on 2025-03-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nene", "0005_remove_herocarousel_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
